require File.dirname(__FILE__) + '/../../../../config/boot.rb'
require File.dirname(__FILE__) + '/../../../../config/environment.rb'
require 'test/unit'
require 'rubygems'
require 'active_support'
require 'active_support/test_case'